const ALERT = "ALERT";
const REFETCH_CHATS = "REFECT_CHATS";
const NEW_ATTACHEMENT = "NEW_ATTACHEMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";
const NEW_REQUEST = "NEW_REQUEST";
const NEW_MESSAGE = "NEW_MESSAGE";
const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOP_TYPING";
const CHAT_JOINED = "CHAT_JOINED";
const ONLINE_USER = "ONLINE_USER";
const CHAT_EXITED = "CHAT_EXITED";
export {
  ALERT,
  REFETCH_CHATS,
  NEW_ATTACHEMENT,
  NEW_MESSAGE_ALERT,
  NEW_REQUEST,
  NEW_MESSAGE,
  START_TYPING,
  STOP_TYPING,
  CHAT_EXITED,
  CHAT_JOINED,
  ONLINE_USER,
};
